spring.application.name=reimbursement-management
server.port=8084

# mysql database connection properties
spring.datasource.url=jdbc:mysql://localhost:3306/reimbursement_management
spring.datasource.username=root
spring.datasource.password=Rittik@95174
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# travel planner service URLs
travel.planner.service.base_url = http://localhost:8082/
travel.planner.service.url = api/
travel.planner.service.skip = false

# account management service URLs
account.management.service.base_url = http://localhost:8081/
account.management.service.url = api/
account.management.service.skip = false